# Generated by Django 4.0.3 on 2022-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tesera_alias', models.SlugField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bgg_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
                ('tesera_id', models.IntegerField(unique=True)),
                ('avg_game_time', models.PositiveSmallIntegerField(blank=True)),
                ('min_players_count', models.PositiveSmallIntegerField(blank=True)),
                ('max_players_count', models.PositiveSmallIntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='media/boardgames/')),
            ],
        ),
    ]
