# Generated by Django 4.0.3 on 2022-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='avg_game_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_rating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='photo',
            field=models.ImageField(upload_to='media/boardgames/main_bg_photo/'),
        ),
    ]
